@echo off
REM This script was copletely generated by ChatGPT...

REM Set the path to the virtual environment
set "venv_path=%~dp0LearnedSpectralUnmixing\Scripts"

REM List of datasets and wavelengths
set "datasets=BASE"
set "wavelengths=15"

REM Loop through datasets and wavelengths
for %%d in (%datasets%) do (
  for %%w in (%wavelengths%) do (
    echo Running with Dataset: %%d, Wavelength: %%w

    REM Activate the virtual environment
    call "%venv_path%\activate.bat"

    REM Run the Python script
    python train_LSTM_models.py %%d %%w

    REM Deactivate the virtual environment
    call "%venv_path%\deactivate.bat"
  )
)