ALL_MODELS = ['ACOUS', 'BASE', 'BG_0-100', 'BG_60-80', 'BG_H2O', 'HET_0-100', 'HET_60-80', 'ILLUM_5mm', 'ILLUM_POINT',
              'INVIS', 'INVIS_ACOUS', 'INVIS_SKIN', 'INVIS_SKIN_ACOUS', 'MSOT', 'MSOT_ACOUS', 'MSOT_ACOUS_SKIN',
              'MSOT_SKIN', 'RES_0.15', 'RES_0.15_SMALL', 'RES_0.6', 'RES_1.2', 'SKIN', 'SMALL', 'WATER_2cm',
              'WATER_4cm']
